language: node_js
node_js:
  - 0.10
services:
  - redis-server
before_install:
  - sudo apt-get update
  - sudo apt-get install rubygems
  - gem install sass --version 3.2.13
  - gem install compass --version 0.12.2
install:
  - npm install
  - npm install -g grunt-cli