language: node_js
node_js:
  - 0.10
before_install:
  - sudo apt-get update
  - sudo apt-get install rubygems
  - gem install compass
before_script:
  - npm install -g grunt-cli
  - npm install -g bower